### ISSUE TITLE
Limit students in a workshop to the capacity of the workshop

### ISSUE THREAD

**Issue by beszel** [WhitmanCSCapstone/ge-scheduling#2]
Each workshop can only hold so many students, as listed in the Capacity column of the Great Explorations Workshop sheet. If the algorithm tries to put a student into a full workshop, put them in their next favorite workshop instead. If all preferred workshops are full, put them in a random workshop.

**Comment by beszel** [comment]
Chris points out that we need to model the three sessions seperately so they can have different capacity. For example, if a speaker can only do two of their three sessions.

**Comment by Izayuh** [comment]
Treat each workshop session as a different entity.

**Comment by Izayuh** [comment]
We are are of this constraint, and when working on our new matcher, we will do it with this constraint in mind.
