### ISSUE TITLE
Consolidate spreadsheets into one sheet file

### ISSUE THREAD

**Issue by beszel** [WhitmanCSCapstone/ge-scheduling#23]
The output spreadsheet is seperate from the results spreadsheet. If we put these spreadsheets in one sheet file, we'll no longer need to identify the output sheet by name or ID.

I don't know of any drawbacks to this. The user interface will be a bit easier to use, since the client will have everything in tabs at the bottom of the sheet.

**Comment by Izayuh** [comment]
Leave the Workshop sheet separate, but combine the response data spreadsheet with the output data and the pre-assignments spreadsheet into one spreadsheet with multiple sheets.

**Comment by beszel** [comment]
We decided to handle file reading with three functions, two returning arrays of Students and one returning the array of all Workshops.

**Comment by tvu212** [comment]
The pull request is up, all the changes were made in main.
