### ISSUE TITLE
Improve matcher method to consider workshop capacities and minimum workshop fill

### ISSUE THREAD

**Issue by Chris-Pyles** [WhitmanCSCapstone/ge-scheduling#36]
**Is your feature request related to a problem? Please describe.**
The matcher method of the Matcher class currently does not consider workshop capacities, and assigns students to full workshops, nor does it consider the minimum fill for each workshop session.

**Describe the solution you'd like**
The new matcher method should consider student preferences and workshop capacities so that students are assigned to their most preferred workshops, provided they can still fit in those workshops, and every workshop session should reach the minimum fill.

**Describe alternatives you've considered**
There is no alternative, this is LITERALLY the entire project.

**Comment by Izayuh** [comment]
Should have something to show the group by Tuesday (the 10th).

**Comment by beszel** [comment]
Closed by #56
