### ISSUE TITLE
Formatting the Output Sheet to Client Specifications

### ISSUE THREAD

**Issue by beszel** [WhitmanCSCapstone/ge-scheduling#48]
The client has specified a specific format for the output sheet as follows:
First Name, Last Name, Grade, Workshop #, Workshop Name, Workshop Location, Workshop #, Workshop Name, Workshop Location Etc...

**Comment by beszel** [comment]
What will you have by next Monday?

**Comment by tvu212** [comment]
Putting in the pull request now
